### ISSUE TITLE
このエラーが出る原因がわかりません、、、

### ISSUE THREAD

**Issue by monomo123** [mizmizo/ig_hashtag_analyzer#33]
@mizmizo 

アクセス情報登録ボタンを押したら、下のエラーがでてしまいます

explain.html
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>IG Hashtag Analyzer</title>
    <link rel="stylesheet" href="css/style.css">
    <script src="explain.js" defer="defer"></script>
  </head>
  <body>
    <div class="loader" id="loader">
      <div class="spinner"></div>
    </div>
    <div class="header">
      <p class="app-title">IG Hashtag Analyzer</p>
    </div>
    <div class="explain-wrapper">
        <!-- ボタンの位置を調節するための空白部分。ページ実装時にhowto-wrapperに差し替える -->
        <p class="explain-title">アプリ設定</p>
        <p>アクセス情報生成</p>
        <div>
          <div class="explain-con1">
            <p class="explain-con-text">短期アクセストークン</p>
            <p class="explain-con-text">App ID</p>
            <p class="explain-con-text">App Secret</p>
            <p class="explain-con-text">FaceBook Page名</p>
          </div>
          <div class="explain-con1">
            <input class="explain-con-input" type="text">
            <input class="explain-con-input" type="text">
            <input class="explain-con-input" type="text">
            <input class="explain-con-input" type="text">
          </div>
        </div>
        <div>
          <input class="app-button app-explain-button" type="submit" value="アクセス情報生成" onclick="apply()">
        </div>
        <p>アクセス情報</p>
        <div>
          <div class="explain-con2">
            <p class="explain-con-text">永続アクセストークン</p>
            <p class="explain-con-text">ビジネスアカウントID</p>
          </div>
          <div class="explain-con2">
            <form name="form1">
              <input class="explain-con-input" type="text" name="tokenn">
              <input class="explain-con-input" type="text" name="ig_ID">
            </form>
          </div>
        </div>
        <input class="app-button app-explain-button" type="submit" value="アクセス情報登録" onclick="apply()">
        <p class="expllain-title" >分析設定</p>
        <div>
          <div class="explain-con2">
            <p class="explain-con-text">分析する投稿数</p>
            <p class="explain-con-text">人気投稿判定</p>
          </div>
          <div class="explain-other" >
            <input class="explain-con-input-number" type="text">
            <input class="explain-con-input-number" type="text">
          </div>
          <div class="explain-other">
            <p>位以内</p>
          </div>
        </div>
        <input class="app-button app-explain-button" type="button" value="戻る" onclick="cancel()">
    </div>
  </body>
</html>
```
explain.js
```
'use strict';

function cancel() {
    window.log.info('call howto.cancel()');
    window.ipcRenderer.invoke('cancel', '');
}

function apply() {
    window.log.info('call explain.apply()');
    const loader = document.getElementById('loader');
    loader.classList.add('loading');
    window.ipcRenderer.invoke('generatePermanentToken', 'params');
    if (true){
      window.ipcRenderer.invoke('getCurrentSetting', '');
    }
}

function regist() {
    window.log.info('call explain.regist()');
    const loader = document.getElementById('loader');
    loader.classList.add('loading');
    params.igID=document.forms.form1.ig_ID.value;
    params.token=document.forms.form1.tokenn.value;
    window.ipcRenderer.invoke('registerAccessInfo', 'params');
    if (true){
      window.ipcRenderer.invoke('getCurrentSetting', '');
    }
}

function regist_setting(){
    window.log.info('call explain.regist_setting()');
    const loader = document.getElementById('loader');
    loader.classList.add('loading');
    window.ipcRenderer.invoke('registerSetting', 'params');
}
```
![image](https://user-images.githubusercontent.com/52732111/83620531-684adb80-a5c8-11ea-9866-58370b0bca23.png)

**Comment by mizmizo** [comment]
まだ作りかけだと思うのでregist()に関してのみ言うと、
- html側でregist()と間違えてapplyを呼んでる
- formのとこの名前がform1だけど位置的にform2じゃない？
- ```params.igID=document.forms.form1.ig_ID.value;```のとこで先にエラーがでる気がする(paramsを宣言してない、右辺の書き方はgetElementByNameでなくていいのかな？知識不足なので初めて見ました)
- 表記ゆれはバグにつながるのでig_IDとかの変数名はほかの場所に合わせて下さい
- invokeの引数が'params'の文字列になってるので変数の方を入れてあげて下さい
- getCurrentSettingを呼んだあとはinnerHTMLを書き換えてください

デバッグの際は
- メインプロセスの動作 ⇒ User/**USERNAME**/AppData/Roaming/ig_hashtag_analyzer/logs/main.log
- レンダラープロセスの実装エラー ⇒ アプリの開発者ツールのconsole
に情報が出るはずで、今回のもmain.logを読むと何が起きたかわかるはずです(多分tokenもigIDも空になってると思う)

ざっと直すとこんな感じですかね、動作テストはしてないです
```
        <div>
          <div class="explain-con2">
            <p class="explain-con-text">永続アクセストークン</p>
            <p class="explain-con-text">ビジネスアカウントID</p>
          </div>
          <div class="explain-con2">
            <form name="form2">
              <input class="explain-con-input" type="text" name="tokenform">
              <input class="explain-con-input" type="text" name="igIDform">
            </form>
          </div>
        </div>
        <input class="app-button app-explain-button" type="submit" value="アクセス情報登録" onclick="regist()">
```

```

function regist() {
    window.log.info('call explain.regist()');
    const loader = document.getElementById('loader');
    loader.classList.add('loading');
    let resigter_form = document.getElementsByName("form2");
    const params ={"igID": document.getElementsByName("igIDform").value,
                   "token": document.getElementsByName("tokenform").value};
    window.ipcRenderer.invoke('registerAccessInfo', params).then((res) => {
        if(res){
            // if resitration succeeded, load and show current Setting (update only token, igID)
            window.ipcRenderer.invoke('getCurrentSetting', '').then((setting) => {
                register_form.innerHTML =
                    '<input class="explain-con-input" type="text" name="tokenform" value="' + setting.token + '">'
                    + '<input class="explain-con-input" type="text" name="igIDform" value="' + setting.igID + '">';
            });
        } else {
            // if failed, clear forms
            register_form.innerHTML =
                '<input class="explain-con-input" type="text" name="tokenform" value="">'
                + '<input class="explain-con-input" type="text" name="igIDform" value="">';
        }
    });
}
```

**Comment by monomo123** [comment]
ちょっと、やってみます

**Comment by monomo123** [comment]
値を取り出すことができるようになり、dataの中では"is_valid":trueとなっているのにdataを返すだけで終わってしまいます。
上のエラーと関係あるのでしょうか。
main.log
[2020-06-06 20:30:37.969] [info] Start app.
[2020-06-06 20:30:37.989] [info] Setting : C:\Users\nobuaki\AppData\Roaming\npm\node_modules\electron\dist\resources\appsetting.json
[2020-06-06 20:30:37.992] [error] Error: Cannot find module 'C:\Users\nobuaki\AppData\Roaming\npm\node_modules\electron\dist\resources\appsetting.json'
Require stack:
- C:\Users\nobuaki\Desktop\ig_hashtag_analyzer\app\lib\setting_operator.js
- C:\Users\nobuaki\Desktop\ig_hashtag_analyzer\app\main.js
- C:\Users\nobuaki\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7736:16)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Module._load (electron/js2c/asar.js:738:28)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at AppSetting.importFile (C:\Users\nobuaki\Desktop\ig_hashtag_analyzer\app\lib\setting_operator.js:28:29)
    at Object.<anonymous> (C:\Users\nobuaki\Desktop\ig_hashtag_analyzer\app\main.js:30:13)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
[2020-06-06 20:30:37.999] [info] load setting failed. load default...
[2020-06-06 20:30:38.006] [info] setting : {
 "post_num": "9",
 "top_thre": "25",
 "ac": {
  "igID": "",
  "token": ""
 },
 "is_valid": false
}
[2020-06-06 20:30:38.155] [info] OpenWindow : index
[2020-06-06 20:30:38.210] [info] reloadURL : index
[2020-06-06 20:30:40.131] [info] IPC CB : toExplain
[2020-06-06 20:30:40.134] [info] reloadURL : explain
[2020-06-06 20:34:21.665] [info] Quit App by window-all-closed.
[2020-06-06 20:35:02.166] [info] Start app.
[2020-06-06 20:35:02.187] [info] Setting : C:\Users\nobuaki\AppData\Roaming\npm\node_modules\electron\dist\resources\appsetting.json
[2020-06-06 20:35:02.189] [error] Error: Cannot find module 'C:\Users\nobuaki\AppData\Roaming\npm\node_modules\electron\dist\resources\appsetting.json'
Require stack:
- C:\Users\nobuaki\Desktop\ig_hashtag_analyzer\app\lib\setting_operator.js
- C:\Users\nobuaki\Desktop\ig_hashtag_analyzer\app\main.js
- C:\Users\nobuaki\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7736:16)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Module._load (electron/js2c/asar.js:738:28)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at AppSetting.importFile (C:\Users\nobuaki\Desktop\ig_hashtag_analyzer\app\lib\setting_operator.js:28:29)
    at Object.<anonymous> (C:\Users\nobuaki\Desktop\ig_hashtag_analyzer\app\main.js:30:13)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
[2020-06-06 20:35:02.198] [info] load setting failed. load default...
[2020-06-06 20:35:02.203] [info] setting : {
 "post_num": "9",
 "top_thre": "25",
 "ac": {
  "igID": "",
  "token": ""
 },
 "is_valid": false
}
[2020-06-06 20:35:02.352] [info] OpenWindow : index
[2020-06-06 20:35:02.413] [info] reloadURL : index
[2020-06-06 20:35:04.284] [info] IPC CB : toExplain
[2020-06-06 20:35:04.287] [info] reloadURL : explain
[2020-06-06 20:35:21.563] [info] IPC CB : registerAccessInfo
[2020-06-06 20:35:21.567] [info] validateAccessInfo
[2020-06-06 20:35:21.579] [info] gURL : https://graph.facebook.com/v7.0/debug_token?input_token=EAAEC5cEGOl0BAIRVzRKWWfJGo8rDW6cFbS1CSU3nVXAZBm5YfbE4oN7yNWZBBAGG5ntf3uZBybpJa9Fql22Vk6c0ZAZBsF7wngvwBmZAgefDAoSEp6e5DSrhNJ4sJvODlWAocdtJBWx3kGeMKpBgjDgqM64IvJS7juS88CRF6oxHNCuR4LqZCIj&access_token=EAAEC5cEGOl0BAIRVzRKWWfJGo8rDW6cFbS1CSU3nVXAZBm5YfbE4oN7yNWZBBAGG5ntf3uZBybpJa9Fql22Vk6c0ZAZBsF7wngvwBmZAgefDAoSEp6e5DSrhNJ4sJvODlWAocdtJBWx3kGeMKpBgjDgqM64IvJS7juS88CRF6oxHNCuR4LqZCIj
[2020-06-06 20:35:21.820] [info] res : {"data":{"app_id":"284660785887837","type":"PAGE","application":"photo_test","data_access_expires_at":1598063902,"expires_at":0,"is_valid":true,"issued_at":1590288429,"profile_id":"107695217627101","scopes":["pages_show_list","business_management","instagram_basic","instagram_manage_comments","instagram_manage_insights","public_profile"],"granular_scopes":[{"scope":"pages_show_list"},{"scope":"business_management"},{"scope":"instagram_basic"},{"scope":"instagram_manage_comments"},{"scope":"instagram_manage_insights"}],"user_id":"1620822648073773"}}

**Comment by mizmizo** [comment]
まず、まだエラーにはなってないけど、
設定ファイルのパスが```~~ dist\resources\appsetting.json```になってる(NODE_ENVが設定されてない)ので戻るボタンを押してregisterSettingが呼ばれたときにエラーになると思うので気を付けて。

で、mainの動作としては正しくて、
レンダラープロセス側にtrueが送られてるはず(main.js L.253)。
ちょっとログが不親切なので今度書き足しときます。

その後の処理が実行されないのはレンダラープロセス側の処理の問題なので、
そちら側をデバッグしてみてください。
```console.log```を遣えば開発者ツールのconsoleに情報出せるし、```window.log.info```を遣えばrenderer.logに情報出せます。
勘だけど受け取った返信(trueが入ってる)の評価の式が間違ってるんじゃないかと。

**Comment by monomo123** [comment]
コマンドプロンプトでset NODE_ENV=developmentを打ち込んでから、electron.cmd .を打ち込んでいるんですけど、それだけではNODE_ENVは設定されないんでしょうか？

**Comment by monomo123** [comment]
main.js
```
// params = {igID:, token:} <- str
ipcMain.handle('registerAccessInfo', async (event, params) => {
    log.info('IPC CB : registerAccessInfo');
    // 永続トークンのチェック⇒OKなら登録
    const ac = new AccessInfo(params.igID, params.token)
    validateAccessInfo(ac, log)
        .then(() => {
            setting.ac = ac;
            setting.is_valid = true;
            return true; // 成功⇒true, 失敗⇒false
        })
        .catch((err) => {
            logAndShowErr(err);
            return false; // 成功⇒true, 失敗⇒false
        });
});

ipcMain.handle('some-name', async (event, params) => {
  if (params.igID=="111"){
    return true
  }
})
```

explain.js
```
function regist() {
    var igID_kari=document.form2.igIDform.value;
    var token_kari=document.form2.tokenform.value
    const params={igID:String(igID_kari),token:String(token_kari)}
    ipcRenderer.invoke("registerAccessInfo",params).then((res)  => {
      alert(res)
    });
}
```
間違ってたら、本当に申し訳ないのですが、registerAccessInfoがtrueを送ってないのではないかと思います、、
上のコードで実行すると
![image](https://user-images.githubusercontent.com/52732111/84114982-3cb46f00-aa68-11ea-93a9-d210465fb84c.png)

ただ、explain.jsのinvokeのregisterAccessInfoをsome-nameにして実行してみると、trueが送られてくるんですよね、、
![image](https://user-images.githubusercontent.com/52732111/84115079-65d4ff80-aa68-11ea-9df1-26296817cd17.png)

間違ってたら、本当にすみません、、
